### ISSUE TITLE
A special kind of communication with the ECU

### ISSUE THREAD

**Issue by Vladislav-Lavrushkin** [iwanders/OBD9141#46]
Hello, My control unit has special modes and PID, how can I work with this with your library?
![image](https://user-images.githubusercontent.com/131286400/233135863-821b046d-967e-4393-a24f-91fac19d5d73.png)
This is a request from the CASCADE 0.9.4 program.

**Comment by Vladislav-Lavrushkin** [comment]
I make such a request but get no response.
![image](https://user-images.githubusercontent.com/131286400/233136416-7e67a560-729d-4d61-baee-e3cda17730ea.png)

**Comment by Vladislav-Lavrushkin** [comment]
For information, 2 requests. The one on the right is understandable. The one on the left is not clear.
![image](https://user-images.githubusercontent.com/131286400/233137793-8824da47-145c-4d9a-b911-09b2cadbe2e6.png)

**Comment by Vladislav-Lavrushkin** [comment]
I begin to understand.
The request does not consist of 5 bytes, but of 6 bytes.
57 CRC.

**Comment by Vladislav-Lavrushkin** [comment]
Now you need to understand how to send a request of 6 bytes:)

**Comment by Vladislav-Lavrushkin** [comment]
`bool OBD9141::getlongPID(uint8_t pid, uint8_t mode, uint8_t return_length){
    uint8_t message[6] = {0x68, 0x6A, 0xF1,0x22, mode, pid};
    // header of request is 5 long, first three are always constant.

    bool res = this->request(&message, 6, return_length+6);
    // checksum is already checked, verify the PID.

    if (this->buffer[5] != pid){
        return false;
    }
    return res;
}`

I wrote a function but it doesn't work. Help me please.

**Comment by Vladislav-Lavrushkin** [comment]
```
bool OBD9141::getlongPID(uint8_t pid, uint8_t mode, uint8_t return_length){
    uint8_t message[6] = {0x68, 0x6A, 0xF1,0x22, mode, pid};
    // 

    bool res = this->request(&message, 6, return_length+6);
    // checksum is already checked, verify the PID.

    if (this->buffer[5] != pid){
        return false;
    }
    return res;
}
```
I added a function for a long request of 6 bytes. Also added a function for a long answer.
I achieved what I wanted.

**Comment by iwanders** [comment]
I was away from my computer for a few weeks, glad you got it to work by yourself, looks great!

The [request](https://github.com/iwanders/OBD9141/blob/ff2d79538ec177c54da349f5d06b86f6b3bfd524/src/OBD9141.h#L151) method is public, so you could also use a helper function outside of the object, if you want to use the library unmodified. You can retrieve the buffer with [readBuffer](https://github.com/iwanders/OBD9141/blob/ff2d79538ec177c54da349f5d06b86f6b3bfd524/src/OBD9141.h#L184), which is also public. This is the first time I've seen a longer request, so I don't think there's much value in adding it to the library.

@Vladislav-Lavrushkin , is this issue good to be closed?

**Comment by Vladislav-Lavrushkin** [comment]
Yes, the topic can be closed.
